# Generated by Django 5.0.3 on 2024-04-02 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='pregunta',
            field=models.CharField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='solucion',
            field=models.CharField(max_length=3500),
        ),
        migrations.AlterField(
            model_name='respuestacorrecta',
            name='solucion',
            field=models.CharField(max_length=3500),
        ),
        migrations.AlterField(
            model_name='respuestausuario',
            name='respuesta',
            field=models.CharField(max_length=3500),
        ),
    ]
