# Generated by Django 5.0.3 on 2024-10-12 01:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuestacorrectalarga',
            name='ejercicio',
        ),
        migrations.RenameField(
            model_name='ejercicio',
            old_name='id_ejercicio',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='ejercicio',
            name='ejercicio',
        ),
        migrations.RemoveField(
            model_name='ejercicio',
            name='fecha',
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='dia',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='enunciado',
            field=models.TextField(default='Enunciado no disponible'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='imagen_compuesto',
            field=models.ImageField(blank=True, null=True, upload_to='compuestos/'),
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='resolucion',
            field=models.TextField(default='Resolución no disponible'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='respuesta_corta',
            field=models.CharField(default='Respuesta corta no disponible', max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='RespuestaCorrectaCorta',
        ),
        migrations.DeleteModel(
            name='RespuestaCorrectaLarga',
        ),
    ]
