# Generated by Django 5.0.3 on 2024-04-08 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_pregunta_alter_ejercicio_pregunta_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pregunta',
        ),
        migrations.RemoveField(
            model_name='ejercicio',
            name='solucion',
        ),
    ]
