# Generated by Django 5.0.3 on 2024-10-18 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_respuestacorrectalarga_ejercicio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ejercicio',
            name='imagen_compuesto',
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='imagen_enunciado',
            field=models.ImageField(blank=True, null=True, upload_to='enunciados/'),
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='imagen_resolucion',
            field=models.ImageField(blank=True, null=True, upload_to='resoluciones/'),
        ),
    ]
