# Generated by Django 5.0.3 on 2024-10-26 02:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_ejercicio_imagen_compuesto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestausuario',
            name='fecha_envio',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
