# Generated by Django 5.0.3 on 2024-04-17 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_ejercicio_numero_pregunta'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespuestaCorrectaCorta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solucion', models.CharField(max_length=255)),
                ('ejercicio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.ejercicio')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaCorrectaLarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solucion', models.TextField()),
                ('ejercicio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.ejercicio')),
            ],
        ),
        migrations.DeleteModel(
            name='RespuestaCorrecta',
        ),
    ]
