# Generated by Django 5.0.3 on 2024-04-27 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_respuestacorrectacorta_respuestacorrectalarga_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejercicio',
            name='fecha',
            field=models.DateTimeField(default='2024-04-27 19:08:59'),
        ),
    ]
