# Generated by Django 5.0.3 on 2024-04-27 20:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_ejercicio_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejercicio',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
